from __future__ import annotations

from uuid import uuid4

from app.models import ToolManifest, World


class ToolFactory:
    def create_tool(self, world: World, agent_id: str, idea: str) -> ToolManifest:
        if not self._lint_check(idea):
            raise ValueError("lint check failed")
        if not self._security_scan(idea):
            raise ValueError("security scan failed")
        if not self._sandbox_test(idea):
            raise ValueError("sandbox test failed")

        tool = ToolManifest(
            id=str(uuid4()),
            creator_agent_id=agent_id,
            name=idea.replace(" ", "-")[:40],
            description=f"Autogenerated tool for {idea}",
            energy_cost=1.5,
            execution_time=1.0,
            reputation=1.0,
            success_rate=0.6,
            price=4.0,
        )
        world.tool_registry[tool.id] = tool
        world.agents_table[agent_id]["created_tools"].append(tool.id)
        return tool

    def _lint_check(self, _idea: str) -> bool:
        return True

    def _security_scan(self, _idea: str) -> bool:
        return True

    def _sandbox_test(self, _idea: str) -> bool:
        return True
